[technote]
id = "DMTN-311"
series_id = "DMTN"
canonical_url = "https://dmtn-311.lsst.io"
github_url = "https://github.com/lsst-dm/dmtn-311"
github_default_branch = "main"
date_created = 2025-03-24T17:48:01Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Wei"
name.family = "Yang"
internal_id = "yangw"

[[technote.authors.affiliations]]
name = "SLAC National Accelerator Laboratory"
internal_id = "SLAC"
address = "2575 Sand Hill Rd., Menlo Park, CA 94025, USA"
